host: 192.168.2.222
server:
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8
  port: 9008
#org.apache.ibatis.logging.log4j2.Log4j2Impl #
spring:
  rabbitmq:
    virtual-host: test
    host: ${host}
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        ## 开始手动签收
        acknowledge-mode: manual
  data:
    mongodb:
      #uri: mongodb://192.168.2.222:27017
      username: luyi
      password: '123'
      database: search
      port: 27017
      host: ${host}
  redis:
    host: ${host}


#    # 当exchange无法找到任何一个合适的queue时，将消息return给生产者
#    spring.rabbitmq.template.mandatory=true
#    # 必须设置为true，否则消息消息路由失败也无法触发Return回调
#    spring.rabbitmq.publisher-returns=true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"

customize:
  es:
    hosts[0]:
      ip: ${host}
      port: 9200
  thread:
    configs:
      ##配置es消费数据的队列
      es_document_consumer:
        ## 拒绝策略
        rejectedHandler: callerRunsPolicy




